<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_NameDescriptionActionsCProgramming Lang_be61f9</name>
   <tag></tag>
   <elementGuidId>d0e01d63-5eef-4201-87c6-ecfaba5a11d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.orangehrm-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a4d0911d-14fa-4b8e-b402-c5484fffcd98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-container</value>
      <webElementGuid>ab180860-92b7-4a0a-84c9-9b4d81368125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NameDescriptionActionsC#Programming LanguageC/C++Programming LanguageContent CreationMarketing SkillCopywritingMarketing SkillG SuiteProductivity ToolsGoogle AnalyticsMarketing SkillJavaProgramming LanguageJavaScriptProgramming LanguageJIRAProject Management ToolsnamedescriptionOffice SuiteProductivity ToolsOracle 8Oracle 8 descrPerlProgramming LanguagePhotoshopGraphic DesignPHPProgramming LanguagePythonProgramming LanguageReact NativeProgramming LanguageRubyProgramming LanguageSearch Engine Optimization (SEO)Marketing SkillSQLProgramming LanguageSwiftProgramming LanguageTest123Test123Testing DemoTrelloProject Management ToolsUI/UX DesignGraphic DesignWireframingGraphic Design</value>
      <webElementGuid>ac7f2df9-f141-42b2-8c79-58718b8e666b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]/div[@class=&quot;orangehrm-paper-container&quot;]/div[@class=&quot;orangehrm-container&quot;]</value>
      <webElementGuid>bbf53530-574c-4ddf-8f7e-61d7a0f14cc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div/div[3]</value>
      <webElementGuid>097348a6-3a3e-4eb6-9e41-26e950dd9341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]</value>
      <webElementGuid>ec4bfc1c-0905-4c5a-944a-7ba2ab4c5bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'NameDescriptionActionsC#Programming LanguageC/C++Programming LanguageContent CreationMarketing SkillCopywritingMarketing SkillG SuiteProductivity ToolsGoogle AnalyticsMarketing SkillJavaProgramming LanguageJavaScriptProgramming LanguageJIRAProject Management ToolsnamedescriptionOffice SuiteProductivity ToolsOracle 8Oracle 8 descrPerlProgramming LanguagePhotoshopGraphic DesignPHPProgramming LanguagePythonProgramming LanguageReact NativeProgramming LanguageRubyProgramming LanguageSearch Engine Optimization (SEO)Marketing SkillSQLProgramming LanguageSwiftProgramming LanguageTest123Test123Testing DemoTrelloProject Management ToolsUI/UX DesignGraphic DesignWireframingGraphic Design' or . = 'NameDescriptionActionsC#Programming LanguageC/C++Programming LanguageContent CreationMarketing SkillCopywritingMarketing SkillG SuiteProductivity ToolsGoogle AnalyticsMarketing SkillJavaProgramming LanguageJavaScriptProgramming LanguageJIRAProject Management ToolsnamedescriptionOffice SuiteProductivity ToolsOracle 8Oracle 8 descrPerlProgramming LanguagePhotoshopGraphic DesignPHPProgramming LanguagePythonProgramming LanguageReact NativeProgramming LanguageRubyProgramming LanguageSearch Engine Optimization (SEO)Marketing SkillSQLProgramming LanguageSwiftProgramming LanguageTest123Test123Testing DemoTrelloProject Management ToolsUI/UX DesignGraphic DesignWireframingGraphic Design')]</value>
      <webElementGuid>dab0d8fc-dfe5-4f4f-8e36-1d95d00cdb68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
