<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Job CategoryActionsCraft WorkersLaborer_1d5135</name>
   <tag></tag>
   <elementGuidId>c2ccccb6-2744-4d2b-96c3-4571fc83ef9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.orangehrm-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9687ad86-9311-4df5-938e-402b027adf72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-container</value>
      <webElementGuid>7df33604-75ba-4d99-af19-3af9262231a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Job CategoryActionsCraft WorkersLaborers and HelpersOffice and Clerical WorkersOfficials and ManagersOperativesProfessionalsSales WorkersService WorkersstaffTechniciansTest</value>
      <webElementGuid>70fe084e-380f-40a8-b7f5-42ba0342b22c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]/div[@class=&quot;orangehrm-paper-container&quot;]/div[@class=&quot;orangehrm-container&quot;]</value>
      <webElementGuid>d525cfa9-4efe-4de5-8f5e-97fbee937ae5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div/div[3]</value>
      <webElementGuid>2572f345-8a9f-4fb5-b613-902dcc8cf4c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]</value>
      <webElementGuid>1528d3a3-d8b8-4877-840c-606fd2732e3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Job CategoryActionsCraft WorkersLaborers and HelpersOffice and Clerical WorkersOfficials and ManagersOperativesProfessionalsSales WorkersService WorkersstaffTechniciansTest' or . = 'Job CategoryActionsCraft WorkersLaborers and HelpersOffice and Clerical WorkersOfficials and ManagersOperativesProfessionalsSales WorkersService WorkersstaffTechniciansTest')]</value>
      <webElementGuid>85b7771b-88c5-4b58-8adb-3c1783b47ac6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
