<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Employment StatusActionsEmployedFreelan_0dad04</name>
   <tag></tag>
   <elementGuidId>90d2abc9-a825-4b6f-b81b-e976db58ae0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div/div[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '${status_work}' or . = '${status_work}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.orangehrm-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8039fe78-6aad-4df2-99f6-c66d024a4fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-container</value>
      <webElementGuid>d3932a61-1d30-442f-9f33-f4a277d30b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${status_work}</value>
      <webElementGuid>ec4e9649-dde6-45ec-8f33-af4402952ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]/div[@class=&quot;orangehrm-paper-container&quot;]/div[@class=&quot;orangehrm-container&quot;]</value>
      <webElementGuid>b9e769b6-0728-4b40-a626-ecc4e8d80144</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div/div[3]</value>
      <webElementGuid>591d3ef6-354c-4513-b8f4-06065e0198f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]</value>
      <webElementGuid>b67f4f6c-cb32-49c8-b951-5c94bfc9fa34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Employment StatusActionsEmployedFreelanceFull-Time ContractFull-Time PermanentFull-Time ProbationPart-Time ContractPart-Time Internship' or . = 'Employment StatusActionsEmployedFreelanceFull-Time ContractFull-Time PermanentFull-Time ProbationPart-Time ContractPart-Time Internship')]</value>
      <webElementGuid>1360a6bc-7886-4b56-ac34-d9c4782c8c5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
